'use server';

/**
 * @fileOverview Generates initial interview prompts for a given job description using AI.
 *
 * - generateInitialPrompts - A function that generates initial interview prompts.
 * - GenerateInitialPromptsInput - The input type for the generateInitialPrompts function.
 * - GenerateInitialPromptsOutput - The return type for the generateInitialPrompts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInitialPromptsInputSchema = z.object({
  jobDescription: z
    .string()
    .describe('The description of the job for which to generate interview prompts.'),
});
export type GenerateInitialPromptsInput = z.infer<typeof GenerateInitialPromptsInputSchema>;

const GenerateInitialPromptsOutputSchema = z.object({
  initialPrompts: z
    .array(z.string())
    .describe('An array of initial interview prompts generated by the AI.'),
});
export type GenerateInitialPromptsOutput = z.infer<typeof GenerateInitialPromptsOutputSchema>;

export async function generateInitialPrompts(
  input: GenerateInitialPromptsInput
): Promise<GenerateInitialPromptsOutput> {
  return generateInitialPromptsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInitialPromptsPrompt',
  input: {schema: GenerateInitialPromptsInputSchema},
  output: {schema: GenerateInitialPromptsOutputSchema},
  prompt: `You are an AI assistant designed to generate initial interview prompts for a given job description.

  Based on the following job description, generate a list of 5 initial interview prompts that can be used to assess a candidate's suitability for the role.

  Job Description: {{{jobDescription}}}

  Please provide the prompts in a numbered list format.
  `,
});

const generateInitialPromptsFlow = ai.defineFlow(
  {
    name: 'generateInitialPromptsFlow',
    inputSchema: GenerateInitialPromptsInputSchema,
    outputSchema: GenerateInitialPromptsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
